Docker branch
SalnikovMarkiian/OnlineBookStore pull request #10
Opened 2023-11-17 17:39 UTC by SalnikovMarkiian

2023-11-17 20:34 UTC, teract10s requested changes
Good job
Just minor comments

2023-11-17 20:34 UTC, teract10s commented on .env
> +DEBUG_PORT=5005
You haven't to push it to Git Hub. You may delete the file, push, and add it again to a local folder. Maybe you added ".env" to .gitignore after git detects this file.

2023-11-17 20:34 UTC, teract10s commented on .env
> +DEBUG_PORT=5005
Also, you may use these variables in application.properites using ${var_name}

2023-11-19 11:50 UTC, NazarSmith228 approved these changes
LGTM, but pls pay attention to my comments

2023-11-19 11:50 UTC, NazarSmith228 commented on pom.xml
> +            <artifactId>spring-boot-docker-compose</artifactId>
why do you need this?

2023-11-19 11:50 UTC, NazarSmith228 commented on Dockerfile
> +COPY --from=builder online-book-store/application/ ./
I don't see any `application` folder at builder stage

or it is one of default folders after jar extraction?

2023-11-19 11:50 UTC, NazarSmith228 commented on docker-compose.yaml
> +      - MySQL_DATABASE=$MYSQLDB_DATABASE
should it be `MySQL` or `MYSQL` ? 

just seems like a typo

2023-11-19 15:55 UTC, merged