implemented shoppingCart into project
SalnikovMarkiian/OnlineBookStore pull request #8
Opened 2023-11-08 13:18 UTC by SalnikovMarkiian

2023-11-08 20:12 UTC, RedArtelerist requested changes
Good job, let's improve your solution.

2023-11-08 20:12 UTC, RedArtelerist commented on src/main/java/com/example/onlinebookstore/controller/ShoppingCartController.java
> +                                         @RequestBody CreateCartItemRequestDto requestDto) {
You forgot `@Valid` annotation

2023-11-08 20:12 UTC, RedArtelerist commented on src/main/java/com/example/onlinebookstore/controller/ShoppingCartController.java
> +                                          @RequestBody CartItemUpdateRequestDto quantityRequest) {
You forgot `@Valid` annotation

2023-11-08 20:12 UTC, RedArtelerist commented on src/main/java/com/example/onlinebookstore/controller/ShoppingCartController.java
> +    @ResponseStatus(HttpStatus.NO_CONTENT)
Why NO_CONTENT if you return ShoppingCartDto

2023-11-08 20:12 UTC, RedArtelerist commented on src/main/java/com/example/onlinebookstore/dto/shopping/cart/CartItemUpdateRequestDto.java
> +public record CartItemUpdateRequestDto(@NotNull @Positive int quantity) {
NotNull for int?

2023-11-08 20:12 UTC, RedArtelerist commented on src/main/java/com/example/onlinebookstore/model/CartItem.java
> +@Where(clause = "is_deleted = false")
You can think: do we need a soft delete for cart items? If yes you can skip this comment

2023-11-08 20:12 UTC, RedArtelerist commented on src/main/java/com/example/onlinebookstore/model/CartItem.java
> +    @ManyToOne
fetch type Lazy and also maybe add optional=false

2023-11-08 20:12 UTC, RedArtelerist commented on src/main/java/com/example/onlinebookstore/model/CartItem.java
> +    @JoinColumn(name = "shopping_cart_id", nullable = false)
Maybe better add also `optional=false` in `ManyToOne`. I found interesting comment about this, so you can think:

"`optional = false` is only for checking this constraint in runtime. `nullable = false` creates database constraint. For applications, to also set `optional = false` makes sense, because it is evaluated faster than going to database and check that constraint there"

2023-11-08 20:12 UTC, RedArtelerist commented on src/main/java/com/example/onlinebookstore/model/ShoppingCart.java
> +    @OneToOne
Think about optional

2023-11-08 20:12 UTC, RedArtelerist commented on src/main/java/com/example/onlinebookstore/service/shopping/cart/ShoppingCartServiceImpl.java
> +    @Transactional
I don't sure, but I think you will have more requests to DB with Transactional. Instead this, you can use EntityGraph in repository method. This approach definitely generate one SQL query.

2023-11-08 20:12 UTC, RedArtelerist commented on src/main/java/com/example/onlinebookstore/service/shopping/cart/ShoppingCartServiceImpl.java
> +                    return shoppingCartRepository.save(shoppingCartNew);
Move this to separate method

2023-11-08 20:12 UTC, RedArtelerist commented on src/main/java/com/example/onlinebookstore/service/shopping/cart/ShoppingCartServiceImpl.java
> +        cartItemRepository.save(cartItem);
Few comments:
1. What will be if you add item with the same bookId that exist in cart? I guess it add a new entity, but you need update quantity if existing.
2. You can replace cartItem.setShoppingCart(shoppingCart); and shoppingCart.getCartItems().add(cartItem); by helper method in ShoppingCart entity in the same way that you did with remove.
3. And why you don't use mapper to map requestDto to CartItem?

2023-11-08 20:12 UTC, RedArtelerist commented on src/main/java/com/example/onlinebookstore/service/shopping/cart/ShoppingCartServiceImpl.java
> +        return shoppingCartMapper.toDto(cartItem.getShoppingCart());
With Transactional you may not call save method in repository. Check it

```suggestion
        cartItem.setQuantity(quantityDto.quantity());
        return shoppingCartMapper.toDto(shoppingCart);
```

2023-11-08 20:12 UTC, RedArtelerist commented on src/main/java/com/example/onlinebookstore/service/shopping/cart/ShoppingCartServiceImpl.java
> +        return shoppingCartMapper.toDto(shoppingCart);
The same with delete as I mentioned above

2023-11-09 08:06 UTC, SalnikovMarkiian commented on src/main/java/com/example/onlinebookstore/dto/shopping/cart/CartItemUpdateRequestDto.java
> +public record CartItemUpdateRequestDto(@NotNull @Positive int quantity) {
I removed @NotNull, but why we can`t use this annotation?

2023-11-13 10:28 UTC, Elena-Bruyako requested changes
Good job! Let's improve your solution!

2023-11-13 10:28 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookstore/model/ShoppingCart.java
> +    //orfRemove
remove comment

2023-11-13 10:28 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookstore/model/ShoppingCart.java
> +    @OneToMany(mappedBy = "shoppingCart")
```suggestion
    @OneToMany(mappedBy = "shoppingCart", cascade = CascadeType.ALL, orphanRemoval = true)
```

2023-11-13 10:28 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookstore/model/ShoppingCart.java
> +    @EqualsAndHashCode.Exclude
Do you need these annotations?

2023-11-13 10:28 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookstore/service/shopping/cart/ShoppingCartServiceImpl.java
> +                .orElseThrow(() -> new RuntimeException(
RuntimeException is too general exception, use custom one

2023-11-13 10:28 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookstore/model/ShoppingCart.java
> +    private Set<CartItem> cartItems;
```suggestion
    private Set<CartItem> cartItems = new HashSet<>();
```

2023-11-13 10:28 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookstore/service/shopping/cart/ShoppingCartServiceImpl.java
> +                    shoppingCartNew.setCartItems(new HashSet<>());
you can remove this line if you initialise cartItems by fix comment above in ShoppingCart entity

2023-11-14 15:16 UTC, Elena-Bruyako approved these changes

2023-11-15 13:01 UTC, merged